### ISSUE TITLE
Bug with child (hovered rect)

### ISSUE THREAD

**Issue by Sasisda228** [dumitru1216/d-ui#2]
![image](https://github.com/dumitru1216/d-ui/assets/43885390/410c17a1-bf52-4320-abc0-3e29f4452717)
![image](https://github.com/dumitru1216/d-ui/assets/43885390/66ed2349-c51d-4c2b-a91a-29e924e104ce)
red is where my cursor

**Comment by dumitru1216** [comment]
will take care of it

**Comment by dumitru1216** [comment]
#issue fixed
